### PR TITLE
File name clashing on some systems.

### PR DESCRIPTION
**Pull request by szesch**
Fixed files that lead to name clashes on systems with gsettings-scheme-convert
already installed. Building from source doesn't care and just overwrites these files, but installing from a ppa results in dpkg errors.

All files with name clashes have been prefixed by "mate-" and all previous references in source have been changed appropriately.

### CODE REVIEW

**Comment by szesch** [comment]
Also added fix to Ubuntu build script. Fixing a dependency issue.

**Comment by perberos** [comment]
use --enable-gsettings-backend=no to disable gsettings build

**Comment by szesch** [comment]
Ok. a7dac45 and feeb2c0 commits still need to be addressed, though.

**Comment by perberos** [comment]
sorry for the delay, I was wanting how to do that.

**Pull request merged**
